# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SSibsPk9yqQYKlXJUc4Ww8t8s03y5LJz
"""

import math as m
print("Hello and welcome to the newest calculator!!")
while True:
  option = input("What do you want to perform with these two numbers \n 1. Find the remainder \n 2. Finding the quotient\n 3. Find the value of num1 to the power of num2 \n 4. Find the square root of the number \n (enter the number of the task you want to perform):\n ")
  if option.isdigit():
    option = int(option)
  if option == 1:
    num1 = int(input("Enter your first number: "))
    num2 = int(input("Enter your second number: "))
    if num2 != 0:
      quotient = num1 % num2
      print(quotient)
    else:
      print("0 is not a denominator so please enter another number.")
      continue
    break
  elif option == 2:
    num1 = int(input("Enter your first number: "))
    num2 = int(input("Enter your second number: "))
    if num2 != 0:
      quotient = num1 // num2
      print(quotient)
    else:
      print("0 is not a denominator so please enter another number.")
      continue
    break
  elif option == 3:
    num1 = int(input("Enter your first number: "))
    num2 = int(input("Enter your second number: "))
    try:
       y = m.pow(num1, num2)
       print(y)
    except OverflowError:
      print("Make the power a smaller posible value please!")
      continue
    break
  elif option == 4:
    num1 = int(input("Enter your first number: "))
    x = m.sqrt(num1)
    print(x)
    break
  else:
    print("This option is not valid!!")
    resume = input("Do you want to continue (Y/N): \n")
    if resume.upper() == "Y" or resume.upper() == "YES":
      continue
    else:
      break